# Get the connector to dremio with the class DremioQueryMakerJDBC

In [1]:
%run /home/ubuntu/notebooks/covid-prj01-data-analysis/[UTILS]/dremio-access-new.py

dremio = DremioQueryMakerJDBC()
index = dremio.getIndex()
display(index)

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,VIEW_DEFINITION
0,DREMIO,Covid-Lake,Disease_Indicator,"SELECT createdOn, identifier, valueString, val..."
1,DREMIO,Covid-Lake,hospitalizações,"SELECT * FROM ""hospitalizacoes.csv"""
2,DREMIO,Covid-Lake,Institution,SELECT * FROM logical_entity
3,DREMIO,Covid-Lake,News&Trends,SELECT * FROM logical_entity
4,DREMIO,Covid-Lake,Socioeconomic_Factors,"SELECT createdOn, clean_data_to_FLOAT(valueStr..."
5,DREMIO,covidlake-raw,brasil_io,"SELECT *\nFROM ""brasil.io"""
6,DREMIO,covidlake-raw,cities,"SELECT * FROM ""Base Coordenadas Brasil.parquet"""
7,DREMIO,covidlake-raw,fiocruz_infogripe,SELECT * FROM fiocruz_infogripe
8,DREMIO,covidlake-raw,google_trends,"SELECT * FROM ""google_trends.parquet"""
9,DREMIO,covidlake-raw,health_ministry,SELECT * FROM health_ministry
10,DREMIO,covidlake-raw,hospitals_dimension,"SELECT * FROM ""hospitals.parquet"""
11,DREMIO,covidlake-raw,mobility_apple,SELECT * FROM apple_mobility_trends
12,DREMIO,covidlake-raw,mobility_google,"SELECT * FROM ""covid-raw"".mobility.google.""Glo..."
13,DREMIO,covidlake-raw,pebmed,SELECT * FROM pebmed
14,DREMIO,covidlake-raw,wcota,SELECT * FROM wcota
15,DREMIO,covidlake-refined,observations,"SELECT ""date"" as createdOn, 'brasil.io' as ide..."
16,DREMIO,Common Data Model.disease_indicator,global_dataset,"SELECT createdOn, identifier, valueString, val..."
17,DREMIO,covidlake-raw.ans,demandas_dos_consumidores_nip,SELECT * FROM demandas_dos_consumidores_nip
18,DREMIO,covidlake-raw.BigDataCorp,BDCnewsCOVID,"SELECT * FROM ""BDCnewsCOVID.parquet"""
19,DREMIO,covidlake-raw.BigDataCorp,treatedBDCcompanies,"SELECT STATE, CASE WHEN regexp_like(CASE WHEN ..."
20,DREMIO,covidlake-raw.BigDataCorp,treatedBDCpeople,"SELECT STATE, EMPLOYMENT_STABILITY_2020_01_01,..."
21,DREMIO,covidlake-raw.datasus,cadasto_nacional_de_estabelecimentos_de_saude_...,"SELECT * FROM ""cadasto_nacional_de_estabelecim..."
22,DREMIO,covidlake-raw.datasus,cadasto_nacional_de_estabelecimentos_de_saude_...,"SELECT * FROM ""cadasto_nacional_de_estabelecim..."
23,DREMIO,covidlake-raw.datasus,cobertura_estimada_da_populacao_residente_pela...,"SELECT * FROM ""cobertura_estimada_da_populacao..."
24,DREMIO,covidlake-raw.datasus,distribuicao_das_equipes_de_saude_da_familia_esf,"SELECT * FROM ""distribuicao_das_equipes_de_sau..."
25,DREMIO,covidlake-raw.datasus,distribuicao_de_agentes_comunitarios_de_saude_acs,"SELECT * FROM ""distribuicao_de_agentes_comunit..."
26,DREMIO,covidlake-raw.datasus,distribuicao_dos_nucles_de_apoio_a_saude_da_fa...,"SELECT * FROM ""distribuicao_dos_nucles_de_apoi..."
27,DREMIO,covidlake-raw.datasus,distribuicao_unidades_basicas_de_saude_em_func...,"SELECT * FROM ""distribuicao_unidades_basicas_d..."
28,DREMIO,covidlake-raw.datasus,distribuicao_unidaes_basicas_de_saude_existent...,"SELECT * FROM ""distribuicao_unidaes_basicas_de..."
29,DREMIO,covidlake-raw.datasus,numero_de_equipes_da_saude_da_familia_esf,"SELECT * FROM ""numero_de_equipes_da_saude_da_f..."
30,DREMIO,covidlake-raw.datasus,numero_de_equipes_de_agentes_comunitarios_de_s...,"SELECT * FROM ""numero_de_equipes_de_agentes_co..."
31,DREMIO,covidlake-raw.datasus,numero_de_unidades_basicas_de_saude_em_constru...,"SELECT * FROM ""numero_de_unidades_basicas_de_s..."
32,DREMIO,covidlake-raw.transparencia,transparencia_auxilio_emergencial_abril,"SELECT * FROM ""abril_auxilio_emergencial.parquet"""
33,DREMIO,covidlake-raw.transparencia,transparencia_auxilio_emergencial_julho,"SELECT * FROM ""julho_auxilio_emergencial.parquet"""
34,DREMIO,covidlake-raw.transparencia,transparencia_auxilio_emergencial_junho,"SELECT * FROM ""julho_auxilio_emergencial.parquet"""
35,DREMIO,covidlake-raw.transparencia,transparencia_auxilio_emergencial_maio,"SELECT * FROM ""maio_auxilio_emergencial.parquet"""
36,DREMIO,Common Data Model.disease_indicator.brasil_io,logical_entity,"SELECT *\nFROM ""standard_entities"".Observation..."
37,DREMIO,Common Data Model.disease_indicator.brasil_io,physical_entity,"SELECT index, TO_CHAR(TO_DATE(nested_0.""date"",..."
38,DREMIO,Common Data Model.disease_indicator.health_min...,logical_entity,"SELECT *\nFROM ""standard_entities"".Observation..."
39,DREMIO,Common Data Model.disease_indicator.health_min...,physical_entity,"SELECT src2.*, location_id\nFROM (\n SELECT..."
40,DREMIO,Common Data Model.disease_indicator.wcota,logical_entity,"SELECT *\nFROM ""standard_entities"".Observation..."
41,DREMIO,Common Data Model.disease_indicator.wcota,physical_entity,"SELECT src2.*, location_id\nFROM (\n SELECT..."
42,DREMIO,Common Data Model.Institutions.hospitals_register,logical_entity,"SELECT userGroupId, name, localeId, loc.*\nFRO..."
43,DREMIO,Common Data Model.Institutions.hospitals_register,physical_entity,"SELECT nested_1.CO_UNIDADE AS CO_UNIDADE, nest..."
44,DREMIO,Common Data Model.news_trends.google_trends,logical_entity,SELECT * FROM Observation
45,DREMIO,Common Data Model.news_trends.google_trends,physical_entity,"SELECT * FROM ""google_trends.parquet"""
46,DREMIO,Common Data Model.socioeconomic_factors.ipeadata,logical_entity,SELECT * FROM Observation
47,DREMIO,Common Data Model.socioeconomic_factors.ipeadata,physical_entity,"SELECT index, ipeadata.""DATE"" AS ""DATE"", ipead..."
48,DREMIO,Common Data Model.disease_indicator.brasil_io....,Location,"SELECT location_id as locationId, '' as addres..."
49,DREMIO,Common Data Model.disease_indicator.brasil_io....,Observation,"SELECT ""date"" as createdOn, 'brasil.io' as ide..."
50,DREMIO,Common Data Model.disease_indicator.health_min...,Location,"SELECT location_id as locationId, '' as addres..."
51,DREMIO,Common Data Model.disease_indicator.health_min...,Observation,"SELECT ""date"" as createdOn, 'health_ministry' ..."
52,DREMIO,Common Data Model.disease_indicator.wcota.stan...,Location,"SELECT location_id as locationId, country as a..."
53,DREMIO,Common Data Model.disease_indicator.wcota.stan...,Observation,"SELECT ""date"" as createdOn, 'wcota' as identif..."
54,DREMIO,Common Data Model.Institutions.hospitals_regis...,Location,"SELECT CO_UNIDADE AS organizationId, \n ..."
55,DREMIO,Common Data Model.Institutions.hospitals_regis...,Organization,"SELECT CO_UNIDADE AS organizationId, CO_CNES A..."
56,DREMIO,Common Data Model.news_trends.google_trends.st...,Observation,"SELECT ""Date"" as createdOn, CAST(Medicamento a..."
57,DREMIO,Common Data Model.socioeconomic_factors.ipeada...,Observation,"SELECT ""DATE"" as createdOn, ""VALUE"" as valueSt..."

In [27]:
raw_index = dremio.getRawIndex()
display(raw_index.head(70).tail(20))

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE
50,DREMIO,covid-raw.datasus,distribuicao_de_agentes_comunitarios_de_saude_...,TABLE
51,DREMIO,covid-raw.datasus,distribuicao_dos_nucles_de_apoio_a_saude_da_fa...,TABLE
52,DREMIO,covid-raw.datasus,distribuicao_unidades_basicas_de_saude_em_func...,TABLE
53,DREMIO,covid-raw.datasus,distribuicao_unidaes_basicas_de_saude_existent...,TABLE
54,DREMIO,covid-raw.datasus,numero_de_equipes_da_saude_da_familia_esf.csv,TABLE
55,DREMIO,covid-raw.datasus,numero_de_equipes_de_agentes_comunitarios_de_s...,TABLE
56,DREMIO,covid-raw.datasus,numero_de_unidades_basicas_de_saude_em_constru...,TABLE
57,DREMIO,covid-raw.hospitalizacoes,hospitalizacoes.csv,TABLE
58,DREMIO,covid-raw.hospitals,estado.parquet,TABLE
59,DREMIO,covid-raw.hospitals,health_establishment.parquet,TABLE
60,DREMIO,covid-raw.hospitals,hospitals.parquet,TABLE
61,DREMIO,covid-raw.hospitals,municipio.parquet,TABLE
62,DREMIO,covid-raw.ibge,RELATORIO_DTB_BRASIL_DISTRITO.parquet,TABLE
63,DREMIO,covid-raw.ipeadata,birth_rate.parquet,TABLE
64,DREMIO,covid-raw.ipeadata,dolar_ratio.parquet,TABLE
65,DREMIO,covid-raw.ipeadata,embi_risk.parquet,TABLE
66,DREMIO,covid-raw.ipeadata,employees_amount.parquet,TABLE
67,DREMIO,covid-raw.ipeadata,fertility_rate.parquet,TABLE
68,DREMIO,covid-raw.ipeadata,financial_credit.parquet,TABLE
69,DREMIO,covid-raw.ipeadata,financial_default.parquet,TABLE

# Get tables by index number

In [4]:
health_ministry = dremio.getTable(2)
health_ministry.head()

    createdOn valueString valueType_display
0  2018-01-07          51       medicamento
1  2018-01-14          48       medicamento
2  2018-01-21          51       medicamento
3  2018-01-28          53       medicamento
4  2018-02-04          54       medicamento

In [28]:
ibge = dremio.getRawTable(62)
ibge.head()

,UF,Nome_UF,Mesorregião Geográfica,Nome_Mesorregião,Microrregião Geográfica,Nome_Microrregião,Município,Código Município Completo,Nome_Município,Distrito,Código de Distrito Completo,Nome_Distrito,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,5,110001505,Alta Floresta D'Oeste,None,None,None
1,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,15,110001515,Filadélfia d'Oeste,None,None,None
2,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,20,110001520,Izidolândia,None,None,None
3,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,25,110001525,Nova Gease d'Oeste,None,None,None
4,11,Rondônia,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,30,110001530,Rolim de Moura do Guaporé,None,None,None

# Make Custom Queries

In [3]:
query = """
SELECT estado, count(*) AS "count" 
FROM "covidlake-raw"."health_ministry" 
GROUP BY estado
;"""
counts = dremio.querySQL(query)
counts.head()

  estado  count
0     PB     98
1     BA     98
2     DF     98
3     AM     98
4     CE     98

# Get Catalog Information using HTTP API

In [36]:
dremio.querySQL("""SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'Covid-Lake';""")

  TABLE_SCHEMA             TABLE_NAME
0   Covid-Lake            Institution
1   Covid-Lake  Socioeconomic_Factors
2   Covid-Lake      Disease_Indicator
3   Covid-Lake            News&Trends
4   Covid-Lake        hospitalizações

In [51]:
dremio_api = DremioQueryBuilderHTTP()
def getMetadata():
    table_name = "Socioeconomic_Factors"
    query_stages = "catalog"
    stages = {stage["path"][0]:stage["id"] for stage in dremioAPI.get(query_stages)["data"]}
    query_tables = "catalog/{}".format(stages["Covid-Lake"])
    tables = {table["path"][1]:table["id"] for table in dremioAPI.get(query_tables)["children"]}
    query_wiki = "catalog/{}".format(tables[table_name])
    return dremio_api.get(query_wiki)
getMetadata()

{'entityType': 'dataset',
 'id': '4bb45146-0b42-4f00-9822-dbfecca2242f',
 'type': 'VIRTUAL_DATASET',
 'path': ['Covid-Lake', 'Socioeconomic_Factors'],
 'createdAt': '2020-06-05T23:10:19.929Z',
 'tag': '0',
 'sql': 'SELECT createdOn, clean_data_to_FLOAT(valueString, 1, 0, 0) AS valueString, valueType_display\nFROM "Common Data Model".socioeconomic_factors.ipeadata.logical_entity\n WHERE is_clean_data(valueString, 1, \'FLOAT\')',
 'sqlContext': ['Common Data Model', 'socioeconomic_factors', 'ipeadata'],
 'fields': [{'name': 'createdOn', 'type': {'name': 'VARCHAR'}},
  {'name': 'valueString', 'type': {'name': 'DOUBLE'}},
  {'name': 'valueType_display', 'type': {'name': 'VARCHAR'}}]}

## Use catalog/{id} to get ids from inside the sources or to the data types from a view or table

In [40]:
query = """catalog/6a04e127-872d-402a-a308-896a26562235"""

tables

{'Disease_Indicator': 'c2f17299-e315-408c-8a82-61357599080c',
 'hospitalizações': '22336014-21ad-4b16-bcbf-cff319df5d88',
 'Institution': 'e74fff06-294f-418a-9b02-b89662645260',
 'News&Trends': '4ea028f5-4c1b-4c25-a7e3-1b2146b7d4d8',
 'Socioeconomic_Factors': '4bb45146-0b42-4f00-9822-dbfecca2242f'}

## Use catalog/{id}/collaboration/tag or catalog/{id}/collaboration/wiki to retrive written description about that dataset

In [34]:
query = """catalog/73cbfbdd-a3dc-4446-9e6f-3c4a50982912/collaboration/wiki"""
dremioAPI.get(query)

{'text': '# Sources: brasil.io, wcota and health_ministry\n\n# Formas de extração: Diária\n\n# Entidades: Disease Indicators\n\n# Mapeamento de colunas\n\n| campo              | tipo de dado | descrição                       |\n|--------------------|:------------:|---------------------------------|\n| createdOn          |     Date     | data de criação                 |\n| identifier         |    String    | base de dados de origem do dado |\n| valueString        |    Numeric   | valor da variável               |\n| valueType_display  |    String    | informação analisada (variável) |\n| addressCountry     |    String    | país                            |\n| adressState        |    String    | sigla do estado                 |\n| adressCity         |    String    | cidade                          |\n| adressType_display |    String    | tipo de unidade federativa      |\n\n# Mapeamento baseado nos datasets abaixo catalogados:\n\n## Dataset 1\n\n### brasil.io\n\n\n|    | campo                          | tipo de dado | descrição                                                                              |\n|----|--------------------------------|:------------:|----------------------------------------------------------------------------------------|\n| 0  | index                          |     int64    | ID da linha                                                                            |\n| 1  | date                           |    object    | data de coleta dos dados no formato YYYY-MM-DD                                         |\n| 2  | state                          |    object    | sigla da unidade federativa (estado)                                                   |\n| 3  | city                           |    object    | nome do município                                                                     |\n| 4  | place_type                     |    object    | tipo de localidade (estado ou cidade)                                                  |\n| 5  | confirmed                      |     int64    | número de casos confirmados                                                            |\n| 6  | deaths                         |     int64    | número de mortes                                                                       |\n| 7  | order_for_place                |     int64    | ordem do registro para este local                                                    |\n| 8  | is_last                        |     bool     | campo lógico (True ou False) que indica se esse registro é o mais novo para esse local |\n| 9  | estimated_population_2019      |    float64   | população estimada em 2019                                                             |\n| 10 | city_ibge_code                 |    float64   | código do IBGE da cidade                                                               |\n| 11 | confirmed_per_100k_inhabitants |    float64   | número de casos confirmados a cada 100 mil                                             |\n| 12 | death_rate                     |    float64   | taxa de mortalidade (mortes/confirmados)                                               |\n| 13 | location_id                    |     int64    | ID da localidade       \n\n\n\n#### Observações:\n\nO nome do município pode estar em branco quando o registro é referente ao estado, pode ser preenchido com Importados/Indefinidos também\nO registro do local referente ao primeiro boletim em que esse local aparecer será contabilizado como 1 e os demais boletins incrementarão esse valor\n\n## Dataset 2\n\n### health_ministry (Ministério da Saúde)\n\n\n| campo            | tipo de dado | descrição                                 |\n|------------------|:------------:|-------------------------------------------|\n| index            |     int64    | ID da linha                               |\n| regiao           |    object    | região do país                            |\n| estado           |    object    | estado                                    |\n| date             |    object    | data                                      |\n| casosNovos       |     int64    | número de novos casos registrados         |\n| casosAcumulados  |     int64    | número de casos acumulados até esta data  |\n| obitosNovos      |     int64    | número de novas mortes registradas        |\n| obitosAcumulados |     int64    | número de mortes acumuladas até esta data |\n| location_id      |     int64    | ID da localidade                          |\n\n## Dataset 3\n                                                                                                                                                   \n### wcota\n\n\n| campo                           | tipo de dado | descrição                                            |\n|---------------------------------|:------------:|------------------------------------------------------|\n| index                           |     int64    | ID da linha                                          |\n| date                            |    object    | data                                                 |\n| country                         |    object    | país                                                 |\n| state                           |    object    | estado                                               |\n| city                            |    object    | cidade                                               |\n| ibgeID                          |     int64    | ID do IBGE                                           |\n| newDeaths                       |     int64    | número de novas mortes registradas                   |\n| deaths                          |     int64    | número de novas mortes acumuladas até esta data      |\n| newCases                        |     int64    | número de novos casos registrados                    |\n| totalCases                      |     int64    | número total de casos registrados até esta data      |\n| deaths_per_100k_inhabitants     |    float64   | número de mortes a cada 100 mil habitantes           |\n| totalCases_per_100k_inhabitants |    float64   | número total de mortes a cada 100 mil habitantes     |\n| deaths_by_totalCases            |    float64   | relação entre o número de mortes e o total de mortes |\n| last_info_date                  |    object    | data da última atualização dos dados                 |\n| epi_week                        |    float64   | semana da epidemia                                           |\n| cod_RegiaoDeSaude               |    float64   | código da região de saúde                            |\n| name_RegiaoDeSaude              |    object    | nome da região de saúde                              |\n| _source                         |    object    | fonte dos dados                                      |\n| location_id                     |     int64    | ID da localidade                                     |\n',
 'version': 6}